### ISSUE TITLE
Allow table columns to wrap text

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sphinx-theme#4]
RST tables in the current theme won't correctly wrap column content, cutting off the content from the viewer.  For example:

![image](https://cloud.githubusercontent.com/assets/121180/21556209/94a55820-cdd3-11e6-8f46-8f3a44a04cec.png)

They need to wrap, so the above should look like this:

![image](https://cloud.githubusercontent.com/assets/121180/21556214/9f6e721e-cdd3-11e6-8f11-f948e44f2950.png)

**Comment by rdegges** [comment]
Merged in the PR to fix this. Thanks @lhazlewood! <3
